/**
 * Created by eivhy on 20.12.2015.
 */
public class pe002 {

    public int run() {

        /*
         * Problem: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
         * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
         * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
         * find the sum of the even-valued terms.
         */

        int firstN = 1;
        int secondN = 2;
        int currentN = 0;
        int fibSumEven = 2;



        for (int e = 2; fibSumEven <  4000000; e++) {

            currentN = firstN + secondN;

            firstN = secondN;

            secondN = currentN;

            if (currentN % 2 == 0) fibSumEven += currentN;

        }

        return fibSumEven;

    }

}
